from flask_babel import _


def get_errors():
    """
    """
    errors_dict = {
        'ReadCsvError': _('Inputed csv file not valid.'),
        'ReadDatasetFromFileError': _('File not valid'),
        'AddInDB': _('Failed to add object in database.'),
        'UpdateInDB': _('Failed to Update object in database.'),
        'DeleteInDB': _('Failed to delete object in database.'),
        'ModelNameNotSet': _('The name of the model is not set'),
        'ModelNameAlreadyUsed': _('The model name is already used.'),
        'ModelPathNoType': _('You need to specify a model type with the path'),
        'ModelPathNotExists': _('The model path is not pointing to a file.'),
        'ModelPathCantOpen': _('Impossible to open the model file.'),
        'ModelPathNoPredictFunction': _('The model has no predict function.'),
        'ModelFileTypeNotValid': _('Model file type is not a valid one, please use one of the following : pickle or joblib'),
        'DatasetNameNotSet': _('The name of the dataset is not set'),
        'DatasetNameAlreadyUsed': _('This dataset name is already used.'),
        'DatasetPathNotExists': _('The dataset path is not pointing to a file.'),
        'DatasetPathExtension': _('The dataset extension is not valid.'),
        'DatasetPathSepNotValid': _('The dataset separator is not valid.'),
        'DatasetPathEncodingNotValid': _('The dataset encoding is not valid.'),
        'DatasetPathCantOpen': _('Impossible to open the dataset file. Check that you can open your file with an other application.'),
        'DatasetColumnNotFound': _(' column not found in the data.'),
        'DatasetModelTypeNotValid': _('The dataset model type is not valid, please use one of the following : binary-classification, multiclass-classification or regression'),
        'ModelDatasetNameNotValid': _('This Dataset does not exist in the database.'),
        'ModelDatasetNoModelColumns': _('The model columns are not set.'),
        'ModelDatasetModelColumnsNotValid': _('The model columns does not match with the loaded model please use the same number of features.'),
        'ModelDatasetNoModel': _('You need to use a valid model before linking it with a Dataset'),
        'ProjectNameNotSet': _('The name of the project is not set.'),
        'ProjectNameAlreadyUsed': _('This project name is already used.'),
        'ProjectDatasetNameNotValid': _('This Dataset does not exist in the database.'),
        'DatasetSepNotSet': _('The separator of the dataset is not set'),
        'DatasetEncodingNotSet': _('The encoding of the dataset is not set'),
        'DatasetEncodingNotValid': _('The dataset encoding is not valid, please check valid Python encodings.'),
        'PandasProfMinimalNotSet': _('The minimal argument is not set.'),
        'PandasProfMinimalNotValid': _('The minimal argument has to be Yes or No.'),
        'PandasProfExplorativeNotSet': _('The explorative argument is not set.'),
        'PandasProfExplorativeNotValid': _('The explorative argument has to be Yes or No.'),
        'PandasProfNrowsNotValid': _('You need to use an integer.'),
        'PandasProfNrowsOverLimit': _('The number of rows is inserted is greater than the length of the dataset.'),
        'SustainableTimeNotSet': _('The time argument is not set.'),
        'SustainableTimeNotValid': _('The time argument has to be a number.'),
        'SustainableTimeNotPositive': _('The time argument must be positive.'),
        'SustainableLocationNotSet': _('The location argument is not set.'),
        'SustainableLocationNotValid': _('The location argument has to be a string.'),
        'SustainableLocationNotInList': _('The location argument must be a valid country.'),
        'SustainableWattsNotSet': _('The watts argument is not set.'),
        'SustainableWattsNotValid': _('The watts argument has to be a number.'),
        'SustainableWattsNotPositive': _('The watts argument must be positive.'),
        }

    return errors_dict
